[[headers]]
  # Apply CORS to all federated JS assets
  for = "/assets/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
