[build]
  command = "pnpm run build:remote"
  publish = "apps/remote/dist"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
